---
- name: Install LAMP in the remote servers
  hosts: all
  tasks:
    - name: Install LAMP
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
      - httpd
      - mariadb-server
      - php

    - name: Start services
      service:
         name: "{{ item }}"
         state: started
         enabled: true
      with_items:
      - httpd
      - mariadb
